# all available options: https://goreleaser.com/customization/
project_name: summon-aws-secrets

before:
  hooks: []

builds:
  - id: summon-aws-secrets
    binary: summon-aws-secrets
    env:
      - CGO_ENABLED=0
    goos:
      - 'darwin'       # MacOS
      - 'freebsd'
      - 'linux'
      - 'netbsd'
      - 'openbsd'
      - 'solaris'
      - 'windows'
    goarch:
      - amd64
    ldflags: []
  - id: summon-aws-secrets-arm
    binary: summon-aws-secrets
    env:
      - CGO_ENABLED=0
    goos:
      - 'darwin'       # MacOS
    goarch:
      - arm64
    ldflags: []


archives:
  - id: summon-aws-secrets
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - README.md
      - LICENSE
      - SECURITY.md

brews:
  - description: AWS Secrets Manager provider for Summon
    homepage: https://github.com/cyberark/summon-aws-secrets
    url_template: https://github.com/cyberark/summon-aws-secrets/releases/download/v{{.Version}}/summon-aws-secrets-{{ tolower .Os }}-{{ tolower .Arch }}.tar.gz
    install: |
      target = lib/"summon"
      target.install "summon-aws-secrets"
    test: |
      system lib/"summon"/"summon-aws-secrets", "-v"

    tap:
      owner: cyberark
      name: homebrew-tools
    skip_upload: true

checksum:
  name_template: 'SHA256SUMS.txt'

release:
  disable: true

changelog:
  skip: true
