version: '2'
services:
  builder:
    build: .
    image: summon-aws-secrets-builder
    entrypoint: /usr/local/go/bin/go
    command: build -v
    volumes:
      - ./output:/go/src/github.com/cyberark/summon-aws-secrets/output
    environment:
      GOOS:
      GOARCH:

  tester:
    build: .
    image: summon-aws-secrets-tester
    ports:
      - "8080"
    entrypoint: /bin/bash
    command: './test-entrypoint.sh'
    volumes:
      - .:/go/src/github.com/cyberark/summon-aws-secrets

